version: '3.8'

services:
  konnkt_db:
    image: postgres:17.4-alpine
    ports:
      - 16666:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: konnkt
      POSTGRES_PASSWORD: pass
    volumes:
      - konnkt-db-vol:/var/lib/postgresql/data

  auth-service:
    build: 
      context: ./konnkt_auth
      dockerfile: Dockerfile
    depends_on:
      - konnkt_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://konnkt_db:16666/konnkt
      SPRING_DATASOURCE_USERNAME: konnkt
      SPRING_DATASOURCE_PASSWORD: pass
    ports:
      - "8081:8081"

  backend-service:
    build:
      context: ./konnkt_backend
      dockerfile: Dockerfile
    depends_on:
      - konnkt_db
      - auth-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://konnkt_db:16666/konnkt
      SPRING_DATASOURCE_USERNAME: konnkt
      SPRING_DATASOURCE_PASSWORD: pass
    ports:
      - "8082:8082"

  database-service:
    build:
      context: ./konnkt_database
      dockerfile: Dockerfile
    depends_on:
      - konnkt_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://konnkt_db:16666/konnkt
      SPRING_DATASOURCE_USERNAME: konnkt
      SPRING_DATASOURCE_PASSWORD: pass
    ports:
      - "8083:8083"

volumes:
  konnkt-db-vol: