version: '3.8'

services:
  konnkt_db:
    image: postgres:17.4-alpine
    ports:
      - 16666:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: konnkt
      POSTGRES_PASSWORD: pass
    volumes:
      - konnkt-db-vol:/var/lib/postgresql/data

  auth-service:
    build: 
      context: ./konnkt_auth
      dockerfile: Dockerfile
    depends_on:
      - konnkt_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://konnkt_db:5432/postgres
      SPRING_DATASOURCE_USERNAME: konnkt
      SPRING_DATASOURCE_PASSWORD: pass
    ports:
      - "8091:8091"

  backend-service:
    build:
      context: ./konnkt_backend
      dockerfile: Dockerfile
    depends_on:
      - konnkt_db
      - auth-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://konnkt_db:5432/postgres
      SPRING_DATASOURCE_USERNAME: konnkt
      SPRING_DATASOURCE_PASSWORD: pass
    ports:
      - "8092:8092"

  database-service:
    build:
      context: ./konnkt_database
      dockerfile: Dockerfile
    depends_on:
      - konnkt_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://konnkt_db:5432/postgres
      SPRING_DATASOURCE_USERNAME: konnkt
      SPRING_DATASOURCE_PASSWORD: pass
    ports:
      - "8093:8093"
  
  kong:
    image: kong:3.6
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/kong.yml
      KONG_LOG_LEVEL: debug
    volumes:
      - ./kong/kong.yml:/kong/kong.yml
    ports:
      - "8000:8000"   # Kong Proxy
      - "8443:8443"   # Kong Proxy SSL
      - "8001:8001"   # Kong Admin API
      - "8444:8444"   # Kong Admin API SSL
    depends_on:
      - auth-service
      - backend-service
      - database-service

  portainer:
    image: portainer/portainer-ce:2.19.4
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:8.3
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin/servers:/pgadmin4/servers
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - konnkt_db

volumes:
  konnkt-db-vol:
  portainer_data:
  pgadmin_data:
