version: "3.8"

services:
  konnkt_db:
    image: postgres:17.4-alpine
    ports:
      - 16666:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: konnkt
      POSTGRES_PASSWORD: pass
    volumes:
      - konnkt-db-vol:/var/lib/postgresql/data

volumes:
  konnkt-db-vol:
